./python/court_video_text_detect.py \
        --data_type images \
        -if $1 \
        -of ./output/$2 \
        --gpu 0 \
        --det_prototxt /home/ligen/court_recognition/data/test.prototxt \
        --det_model  /home/ligen/court_recognition/data/vgg16_faster_rcnn_on_court_img_iter_100000.caffemodel \
        --ocr_tool  /home/ligen/court_recognition/mqdf/OCRTool \
        --ocr_model /home/ligen/court_recognition/data/template_bimoment_chinese_4_1230train12_3_.dat \
        --limit 5 \
        --interval 20 \
        --recognize 1 \
        --visualize 1
